export const GET_CURRENT_PRODUCT = "GET_CURRENT_PRODUCT"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_PRICE_RANGE_LIST = "GET_PRICE_RANGE_LIST"
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS"