export const GET_CURRENT_PRODUCT_P = "GET_CURRENT_PRODUCT_P"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_PRICE_RANGE_LIST = "GET_PRICE_RANGE_LIST"
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS"
