export const SET_PRODUCTS = "SET_PRODUCTS"
export const LOG_ERROR = "LOG_ERROR"
export const SET_CURRENT_PRODUCT_NAME = "SET_CURRENT_PRODUCT_NAME"
export const SET_APPLIED_FILTERS = "SET_APPLIED_FILTERS"